<html>
<head><title>Index of /weather/alerts/txt/GER/</title></head>
<body>
<h1>Index of /weather/alerts/txt/GER/</h1><hr><pre><a href="../">../</a>
<a href="VHDL30_DWOG_190800">VHDL30_DWOG_190800</a>                                 19-Nov-2024 18:09                2842
<a href="VHDL30_DWOG_191800">VHDL30_DWOG_191800</a>                                 19-Nov-2024 20:59                3911
<a href="VHDL30_DWOG_200200">VHDL30_DWOG_200200</a>                                 20-Nov-2024 04:00                3013
<a href="VHDL30_DWOG_200400">VHDL30_DWOG_200400</a>                                 20-Nov-2024 08:53                2206
<a href="VHDL30_DWOG_200800">VHDL30_DWOG_200800</a>                                 20-Nov-2024 17:54                2926
<a href="VHDL30_DWOG_201800">VHDL30_DWOG_201800</a>                                 20-Nov-2024 19:00                2992
<a href="VHDL30_DWOG_210200">VHDL30_DWOG_210200</a>                                 21-Nov-2024 05:44                3009
<a href="VHDL30_DWOG_210400">VHDL30_DWOG_210400</a>                                 21-Nov-2024 09:53                2875
<a href="VHDL30_DWOG_210800">VHDL30_DWOG_210800</a>                                 21-Nov-2024 09:30                2940
<a href="VHDL35_DWOG_191900">VHDL35_DWOG_191900</a>                                 19-Nov-2024 20:00                1923
<a href="VHDL35_DWOG_200300">VHDL35_DWOG_200300</a>                                 20-Nov-2024 04:00                1923
<a href="VHDL35_DWOG_200900">VHDL35_DWOG_200900</a>                                 20-Nov-2024 09:49                1949
<a href="VHDL35_DWOG_201900">VHDL35_DWOG_201900</a>                                 20-Nov-2024 20:00                1951
<a href="VHDL35_DWOG_210300">VHDL35_DWOG_210300</a>                                 21-Nov-2024 04:00                1953
<a href="VHDL35_DWOG_210900">VHDL35_DWOG_210900</a>                                 21-Nov-2024 10:30                1681
<a href="WUDL99_DWOF_210738">WUDL99_DWOF_210738</a>                                 21-Nov-2024 07:54                1639
</pre><hr></body>
</html>
